spring:
    profiles: 
    active:
    - dev 

---
spring:
    profiles: dev     #开发环境
    application:
      name: shanbuy-config-dev
      
---

spring:
    profiles: test    #测试环境
    application: 
      name: shanbuy-config-test
    
#请保存为UTF-8的格式